pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: runStage2
    type: boolean
    default: false
  - name: runStage3
    type: boolean
    default: false

stages:
  - stage: Stage1
    displayName: "Run Python Script 1"
    variables:
    - group: VG1
    jobs:
      - job: RunPythonScript
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              python3 -m pip install -r requirements.txt
            displayName: "Install Requests Library"

          - script: |
              python3 create_project.py --apiKey $(BRIGHTSEC_API_KEY) --groupIds $(GROUP_IDS) --projectFile $(PROJECT_NAME_FILE)
            displayName: "Run Python Project Creation Script"
            env:
              BRIGHTSEC_API_KEY: $(BRIGHTSEC_API_KEY)
              GROUP_IDS: $(GROUP_IDS)
              PROJECT_NAME_FILE: $(PROJECT_NAME_FILE)
  
  - stage: Stage2
    displayName: "Run Python Script 2"
    condition: eq(variables['runStage2'], 'true')  
    jobs:
      - job: RunSecondPythonScript
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              python3 script2.py
            displayName: "Run Second Python Script"

  - stage: Stage3
    displayName: "Run Python Script 3"
    condition: eq(variables['runStage3'], 'true')  # Conditional for stage 3
    jobs:
      - job: RunThirdPythonScript
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              python3 script3.py
            displayName: "Run Third Python Script"
