trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ProjectCreation
  displayName: 'Create Projects'
  jobs:
  - job: CreateProjectsJob
    displayName: 'Run Python Script to Create Projects'
    steps:
    - checkout: self  # Checkout GitHub repository
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'pwd'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install requests
      displayName: 'Install dependencies'

    - script: |
        python create_project.py
      displayName: 'Run Python Script'

      env:
        BRIGHTSEC_API_KEY: $(BRIGHTSEC_API_KEY)  
        PROJECT_FILE: $(Pipeline.Workspace)/project_name.txt  
        GROUP_IDS: $(GROUP_IDS)  

