trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TestStage
  displayName: 'Test Pipeline Stage'
  jobs:
  - job: TestJob
    displayName: 'Run Hello World Job'
    steps:
    - script: echo "Hello, World!"
      displayName: 'Print Hello World'
