pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: runStage1
    displayName: 'Run Stage 1'
    type: boolean
    default: true

  - name: runStage2
    displayName: 'Run Stage 2'
    type: boolean
    default: true

  - name: runStage3
    displayName: 'Run Stage 3'
    type: boolean
    default: true

variables:
  myVariable: $(myVariable)

stages:
- stage: Stage1
  displayName: 'Stage 1'
  condition: and(succeeded(), eq(variables['runStage1'], 'true'))
  jobs:
  - job: Job1
    steps:
    - script: echo "Running Stage 1 with variable $(myVariable)"

- stage: Stage2
  displayName: 'Stage 2'
  condition: and(succeeded(), eq(variables['runStage2'], 'true'))
  jobs:
  - job: Job2
    steps:
    - script: echo "Running Stage 2 with variable $(myVariable)"

- stage: Stage3
  displayName: 'Stage 3'
  condition: and(succeeded(), eq(variables['runStage3'], 'true'))
  jobs:
  - job: Job3
    steps:
    - script: echo "Running Stage 3 with variable $(myVariable)"
