pool:
  vmImage: 'ubuntu-latest'

variables:
- name: BRIGHTSEC_API_KEY
  value: $(BRIGHTSEC_API_KEY)
- name: GROUP_IDS
  value: auTxkMgnzoeRW9MRdCF5ZQ
- name: PROJECT_NAME_FILE
  value: project_name.txt
- name: PROJECT_ID
  value: tg3G88rPJS3ckSSYPmgHCv
- name: TARGET_URL
  value: https://brokencrystals.com/
- name: NAME_DISCOVERY
  value: Discovery123632
- name: NAME_SCAN
  value: Scan12392039

stages:
- stage: CreateProject
  displayName: 'Create Project'
  jobs:
    - job: RunScriptCreateProject
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            pip install requests
            python3 create_project.py --apiKey $(BRIGHTSEC_API_KEY) --groupIds $(GROUP_IDS) --projectFile $(PROJECT_NAME_FILE)
          displayName: "Create Project"
- stage: CreateDiscovery
  displayName: 'Create Discovery'
  jobs:
    - job: RunScriptCreateDiscovery
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            pip install requests
            python3 create_discovery.py --apiKey $(BRIGHTSEC_API_KEY) --projectId $(PROJECT_ID) --targetUrl $(TARGET_URL) --nameDiscovery $(NAME_DISCOVERY)
          displayName: "Create Discovery"
- stage: RunScan
  displayName: 'Run Scan'
  jobs:
    - job: RunScriptRunScan
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            pip install requests
            python3 run_scan.py --apiKey $(BRIGHTSEC_API_KEY) --projectId $(PROJECT_ID) --targetUrl $(TARGET_URL) --nameScan $(NAME_SCAN)
          displayName: "Run Scan"