pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: CreateProject
    displayName: 'CreateProject'
    type: boolean
    default: false
  # - name: runStage2
  #   displayName: 'Run Stage 2'
  #   type: boolean
  #   default: true
  # - name: runStage3
  #   displayName: 'Run Stage 3'
  #   type: boolean
  #   default: true

variables:
- name: BRIGHTSEC_API_KEY
  value: 0spnuda.nexa.c1goqd3vxnqxzangckjvwsjnyrizhglj
- name: GROUP_IDS
  value: auTxkMgnzoeRW9MRdCF5ZQ
- name: PROJECT_NAME_FILE
  value: project_name.txt
- name: PROJECT_ID
  value: tg3G88rPJS3ckSSYPmgHCv
- name: TARGET_URL
  value: https://brokencrystals.com/
- name: NAME_DISCOVERY
  value: Discovery123

stages:
- stage: CreateProject
  displayName: 'Create Project'
  condition: and(succeeded(), eq(variables['CreateProject'], 'true'))
  jobs:
    - job: RunScriptCreateProject
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            pip install requests
            python3 create_project.py --apiKey $(BRIGHTSEC_API_KEY) --groupIds $(GROUP_IDS) --projectFile $(PROJECT_NAME_FILE)
          displayName: "Create Project"
- stage: CreateDiscovery
  displayName: 'Create Discovery'
  # condition: and(succeeded(), eq(variables['CreateDiscovery'], 'true'))
  jobs:
    - job: RunScriptCreateDiscovery
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            pip install requests
            python3 create_discovery.py --apiKey $(BRIGHTSEC_API_KEY) --projectId $(PROJECT_ID) --targetUrl $(TARGET_URL) --nameDiscovery $(NAME_DISCOVERY)
          displayName: "Create Discovery"
