pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: CreateProject
    displayName: 'CreateProject'
    type: boolean
    default: true

  - name: runStage2
    displayName: 'Run Stage 2'
    type: boolean
    default: true

  - name: runStage3
    displayName: 'Run Stage 3'
    type: boolean
    default: true

variables:
- name: BRIGHTSEC_API_KEY
  value: 0spnuda.nexa.c1goqd3vxnqxzangckjvwsjnyrizhglj
- name: GROUP_IDS
  value: auTxkMgnzoeRW9MRdCF5ZQ
- name: PROJECT_NAME_FILE
  value: project_name.txt

stages:
- stage: CreateProject
  displayName: 'Create Project'
  condition: and(succeeded(), eq(variables['CreateProject'], 'true'))
  jobs:
    - job: RunScriptCreateProject
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
        - script: |
            python3 create_project.py --apiKey $(BRIGHTSEC_API_KEY) --groupIds $(GROUP_IDS) --projectFile $(PROJECT_NAME_FILE)
          displayName: "Create Project"

- stage: Stage2
  displayName: 'Stage 2'
  condition: and(succeeded(), eq(variables['runStage2'], 'true'))
  jobs:
  - job: Job2
    steps:
    - script: echo "Running Stage 2 with variable $(myVariable)"

- stage: Stage3
  displayName: 'Stage 3'
  condition: and(succeeded(), eq(variables['runStage3'], 'true'))
  jobs:
  - job: Job3
    steps:
    - script: echo "Running Stage 3 with variable $(myVariable)"
