name: BrightSec Scan Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  create_project:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run create_project.py
        run: |
          python create_project.py --apiKey ${{ secrets.BRIGHTSEC_API_KEY }} --groupIds ${{ secrets.GROUP_IDS }} --projectFile project_names.txt

  discovery_scan:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run discovery scan
        run: |
          python create_discovery.py --apiKey ${{ secrets.BRIGHTSEC_API_KEY }} --projectId ${{ secrets.PROJECT_ID }} --targetUrl https://your-target-url.com --nameDiscovery "DiscoveryScan"

  scan_entrypoints:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run scan on entry points
        run: |
          python run_ep_scan.py --api_key ${{ secrets.BRIGHTSEC_API_KEY }} --scan_name "My Scan" --project_name "My Project" --project_id ${{ secrets.PROJECT_ID }}

  run_ep_scan_from_file:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run scan from file
        run: |
          python run_ep_scan_from_file.py --api_key ${{ secrets.BRIGHTSEC_API_KEY }} --scan_name "My File Scan" --project_name "My Project" --project_id ${{ secrets.PROJECT_ID }} --entrypoints_file entrypoints.txt

archive_results:
    runs-on: ubuntu-latest
    needs: [create_project, discovery_scan, scan_entrypoints, run_ep_scan_from_file]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create archive file
        run: |
          mkdir -p archive
          cp -r logs/* archive/ || echo "No logs found, skipping"
          cp project_names.txt archive/ || echo "No project_names.txt found, skipping"
          cp entrypoints.txt archive/ || echo "No entrypoints.txt found, skipping"
          tar -czf pipeline_results.tar.gz -C archive .
          echo "Archive created: pipeline_results.tar.gz"

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-results
          path: pipeline_results.tar.gz